name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04


    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 11

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build debug apk
      run: chmod a+x gradlew && ./gradlew clean assembleDebug

    - name: Archive apk
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk

#    - name: Update the InstallPackage
#      run: cp app/build/outputs/apk/debug/app-debug.apk ./InstallPackage/QZCompanionPeloton.apk
      
#    - name: Commit InstallPackage
#      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#      with:    
#         add: './InstallPackage/QZCompanionPeloton.apk'
#         message: 'Updating InstallPackage'
#         push: origin HEAD:master

#    - name: Create release and upload apk
#      uses: underwindfall/create-release-with-debugapk@v2.0.0
#      env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: 1.0.0 #${{ steps.get_version.outputs.VERSION }}
#        asset_path: app/build/outputs/apk/debug/app-debug.apk
#        asset_name: QZCompanionPeloton.apk
#        asset_content_type: application/zip
